# Nombre de la aplicacion
spring.application.name=sipv

# Conexion a MongoDB Atlas
# Spring Boot 4.0 renombro el prefijo: spring.data.mongodb.* -> spring.mongodb.*
spring.mongodb.uri=mongodb+srv://jdurbanocordoba_db_user:CheniA@sipv.yxyobrz.mongodb.net/sipv?appName=SIPV
# Puerto del servidor
server.port=8080

# Ruta de la interfaz de Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html